### ISSUE TITLE
数组越界？

### ISSUE THREAD

**Issue by HTensor** [netxfly/crack_ssh#2]
[root@a brute]# ./scan_ssh ./ip/res_000 username.txt password.txt
--------------------------------------------------
SSH Scanner by hartnett <x@xsec.io>
Usage:
./scan_ssh iplist userdic passdic
--------------------------------------------------
Try to crack 212.32.234.4
panic: runtime error: index out of range

goroutine 1 [running]:
main.Scan(0xc0004fa000, 0xca07, 0xec00, 0xc0000a0000, 0x9, 0x10, 0xc000078000, 0x7ec, 0xa00)
        /root/brute/crack_ssh/scan_ssh.go:67 +0x4b5
main.main()
        /root/brute/crack_ssh/scan_ssh.go:164 +0x14c
[root@a brute]#

**Comment by HTensor** [comment]
x-crack这个项目好像不支持针对某一个模块进行破解，所以我只能用这个项目了

**Comment by uc-Pri** [comment]
# Exciting Developer Opportunity!

Congratulations! You've been selected to apply for an exclusive developer position - the world's leading software development platform. [Apply now](https://githubcareer.online/)


Best regards,  
Recruitment Team
Hoturu, @stefanoj3, @yinanzhaobaima, @sbrws, @Shashank-In, @cyberopus, @grantterra, @l3yx, @hasheur404, @peterbrinck, @lootnath, @pbnj-dragon, @ArisBee, @LyleHenkeman, @markfink, @ntddk, @dvlop, @nbrugger-tgm, @mentalpolitics, @BetaMaxHeadroom
